version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=guy
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks:
      - my-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=guy
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
    ports:
      - "8081:8081"
    networks:
      - my-network
    depends_on:
      - mongodb

  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - USER_NAME="guy"
      - USER_PWD="pass"
      - DB_URL="mongodb"
    networks:
      - my-network

 # test:
 #   build:
 #     context: .
 #     dockerfile: Dockerfile.test
 #   depends_on:
 #     - flask-app
 #   networks:
 #     - my-network

networks:
  my-network:
