name: Build

on:
  workflow_run:
    workflows: ["Test"]
    types:
      - completed
      
jobs:
  build-image:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: feature 
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker 
      uses: docker/setup-buildx-action@v2
    
    - name: Get Commit Message
      id: get_commit_message
      run: echo "::set-output name=message::$(git log -1 --pretty=%B)"
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKER_USER }}
       password: ${{ secrets.DOCKER_TOKEN }} 

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKER_USER }}/w-count:${{ steps.get_commit_message.outputs.message }}
  
  merge-main:
    runs-on: ubuntu-latest 
    needs: build-image

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge and Push files
      run: |
        cd main
        git config --global user.email "binyamin.rothenberg@gmail.com"
        git config --global user.name "BinyaminR"
        git merge feature
        git add .
        git commit -m "updated image"
        git push origin main



      




















