name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
      
jobs:
  pull-repo:
    runs-on: ubuntu-latest 
  
    steps:

    - name: clone CD repo
      uses: actions/checkout@v3
      with:
        repository: BinyaminR/cd.env
        path: main
        token: ${{ secrets.GIT_TOKEN }}
    
    - name: Get Commit Message
      id: get_commit_message
      run: echo "::set-output name=message::$(git log -1 --pretty=%B)"
    
    - name: Commit and Push files
      run: |
        cd main/helm/app-chart && ./update_image.sh ${{ secrets.DOCKER_USER }}/w-count:${{ steps.get_commit_message.outputs.message }}
        git config --global user.email "binyamin.rothenberg@gmail.com"
        git config --global user.name "BinyaminR"
        git add .
        git commit -m "updated image"
        git push origin main
  
  #  - name: Push changes
  #    uses: ad-m/github-push-action@master
  #    with:
  #      github_token: ${{ secrets.GIT_TOKEN }}
  #      branch: "main"
  #      directory: main
      
    
