name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  pull-repo:
    runs-on: ubuntu-latest 
  
    steps:

    - name: clone CD repo
      uses: actions/checkout@v3
      with:
        repository: BinyaminR/cd.env
        path: main
        token: ${{ secrets.GIT_TOKEN }}
    
    - name: Change directory and run script to update image
      run: cd main/helm/app-chart/ && ./update_image.sh binyamin22/w-count:1.0.1

    - name: Commit files
      run: |
        cd main
        git config --local user.email "binyamin.rothenberg@gmail.com"
        git config --local user.name "BinyaminR"
        git commit -a -m "updated image"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GIT_TOKEN }}
        branch: ${{ github.ref }}
