name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest 
    needs: build-image

    steps:

    - name: clone CD repo
      uses: actions/checkout@v3
      with:
        repository: cd.env
        path: main
        token: ${{ secrets.GIT_TOKEN }}
