name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  pull-repo:
    runs-on: ubuntu-latest 
  
    steps:

    - name: clone CD repo
      uses: actions/checkout@v3
      with:
        repository: BinyaminR/cd.env
        path: main
        token: ${{ secrets.GIT_TOKEN }}
    
    - name: test
      run: cd main && ls -l

    - name: Update image
      run:  ./main/helm/app-chart/update_image.sh binyamin22/w-count:1.0.1