name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  pull-repo:
    runs-on: ubuntu-latest 
  
    steps:

    - name: clone CD repo
      uses: actions/checkout@v3
      with:
        repository: BinyaminR/cd.env
        path: main
        token: ${{ secrets.GIT_TOKEN }}
    
    - name: Change to directory with values.yaml
      run: cd main/helm/app-chart/

    - name: Run script to update image
      run: |
        ./update_image.sh binyamin22/w-count:1.0.1