name: CD

on:
  push:
   - main

jobs:
  pull:
    runs-on: ubuntu-latest 
    needs: build-image

    steps:

    - name: Checkout tools repo
      uses: actions/checkout@v3
      with:
       repository: cd.env
       path: main
       token: ${{ secrets.GIT_TOKEN }}   
