name: CI

on:
  push:
    branches:
      - feature
    paths:
      - app.py
      - Dockerfile
      - templates/home.html
      
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    
    - name: Build and start containers
      run: |
        docker-compose up -d --build
      working-directory: . 

    - name: Run Python Tests
      uses: actions/setup-python@v4
      with:
        python-version: 3  
     

    - name: Install dependencies
      run: |
        pip install flask pytest requests
      working-directory: .  

    - name: Run tests
      run: |
        python3 test.py
      working-directory: .  

    - name: Stop and remove containers
      run: |
        docker-compose down
      working-directory: .  
  
  build-image:
    runs-on: ubuntu-latest 
    needs: build-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker 
      uses: docker/setup-buildx-action@v2
    
    - name: Get Commit Message
      id: get_commit_message
      run: echo "::set-output name=message::$(git log -1 --pretty=%B)"
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
       username: ${{ secrets.DOCKER_USER }}
       password: ${{ secrets.DOCKER_TOKEN }} 

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKER_USER }}/w-count:${{ steps.get_commit_message.outputs.message }}
  

    
 
 

    