name: Test

on:
  push:
    branches:
      - feature
    paths:
      - app.py
      - Dockerfile
      - templates/home.html
      
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: feature # Replace 'feature' with the name of the branch you want to check out
     
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    
    - name: Build and start containers
      run: |
        docker-compose up -d --build
      working-directory: . 

    - name: Run Python Tests
      uses: actions/setup-python@v4
      with:
        python-version: 3  
     

    - name: Install dependencies
      run: |
        pip install flask pytest requests
      working-directory: .  

    - name: Run tests
      run: |
        python3 test.py
      working-directory: .  

    - name: Stop and remove containers
      run: |
        docker-compose down
      working-directory: .

      - name: Slack Notification
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#test'
        if: always()  
  
  
  

    
 
 

    