name: Commit

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
      
jobs:
  merge-main:
    runs-on: ubuntu-latest 

    steps:
    - uses: actions/checkout@master

    - name: Merge to main
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: feature
        target_branch: main
        github_token: ${{ secrets.GIT_TOKEN }}

    - name: Push files
      run: |
        git config --global user.email "binyamin.rothenberg@gmail.com"
        git config --global user.name "BinyaminR"
        
        
        git add .
        git commit -m "approved update"
        git push origin main
